---
common:
    host_user: root
    host_password: redhat
    host_ip: "10.66.148.24"
    rhvm_fqdn: rhvm41-vdsm-auto.lab.eng.pek2.redhat.com
    browser: firefox
    test_build: redhat-virtualization-host-4.1-20170727.1

subscription:
    rhn_user: QualityAssurance
    rhn_password: VHVFhPS5TEG8dud
    activation_key: rhevh
    activation_org: "711497"
    satellite_ip: "10.73.75.177"
    satellite_hostname: satellite62.lab.eng.pek2.redhat.com
    satellite_user: admin
    satellite_password: redhat
    ca_path: https://10.73.75.177/pub/katello-ca-consumer-satellite62.lab.eng.pek2.redhat.com-1.0-1.noarch.rpm
    # TODO 

hosted_engine:
    rhvm_appliance_path: http://10.66.10.22:8090/rhevm-appliance/
    storage_type: nfs
    nfs_ip: "10.66.148.11"
    nfs_password: redhat
    he_install_nfs: /home/jiawu/nfs1
    he_data_nfs: /home/jiawu/nfs2
    sd_name: heauto-sd
    he_vm_mac: 52:54:00:57:ef:59
    he_vm_fqdn: rhevh-hostedengine-vm-03.qe.lab.eng.nay.redhat.com
    he_vm_ip: "10.66.148.104"
    he_vm_password: redhat
    engine_password: password
    auto_answer: http://10.73.73.23:8000/run?download=true
    second_host: "10.66.150.175"
    second_password: redhat
    second_vm_fqdn: cockpit-vm
    # TODO

mapper:
    sys_ip_map:
        hp-z620-04.qe.lab.eng.nay.redhat.com: "10.66.148.24"
        hp-z620-05.qe.lab.eng.nay.redhat.com: "10.66.150.175"
        dell-op790-01.qe.lab.eng.nay.redhat.com: "10.66.148.7"
        dell-pet105-02.qe.lab.eng.nay.redhat.com: "10.66.148.10"
    he_vm_map:
        rhevh-hostedengine-vm-01.qe.lab.eng.nay.redhat.com: "52:54:00:05:61:f2"
        rhevh-hostedengine-vm-02.qe.lab.eng.nay.redhat.com: "52:54:00:71:d5:ff"
        rhevh-hostedengine-vm-03.qe.lab.eng.nay.redhat.com: "52:54:00:57:ef:59"
        rhevh-hostedengine-vm-04.lab.eng.pek2.redhat.com: "52:54:00:5e:8e:c7"
        rhevh-hostedengine-vm-05.lab.eng.pek2.redhat.com: "52:54:00:5d:21:64"
        rhevh-hostedengine-vm-06.lab.eng.pek2.redhat.com: "52:54:00:34:04:b0"
    # TODO
